### ISSUE TITLE
Check if new installation of trnascan works

### ISSUE THREAD

**Issue by victor73** [Virome-Collaboration-Group/virome_pipeline#2]
Latest version of container uses a binary package for trnascan-se, which accelerates the build and puts the tool into /usr/bin/tRNAscan-SE instead of under /opt. It also puts the tool on the default $PATH. Probably need to update this repo's software config and test it to make sure it works properly.

**Comment by bjaysheel** [comment]
now using tRNAScan install from .deb, had to rename function call from fastafile() to fasta_file().

**Comment by victor73** [comment]
Does that mean this can be closed?

**Comment by bjaysheel** [comment]
Yes, I didn't see a close option.

Jaysheel
